exports.getTenantListJar86 = function (req, res) {
    console.log("Received get request to get shopping cart");
    res.header("Content-Type: application/json");
    res.send(JSON.stringify(tenants));
  };

  let tenants = [{
    "id": 1,
    "first_name": "George",
    "last_name": "Massimo",
    "email": "gmassimo0@drupal.org",
    "gender": "Genderfluid"
  }, {
    "id": 2,
    "first_name": "Dix",
    "last_name": "Pipe",
    "email": "dpipe1@addtoany.com",
    "gender": "Non-binary"
  }, {
    "id": 3,
    "first_name": "Konstantin",
    "last_name": "Halladey",
    "email": "khalladey2@comsenz.com",
    "gender": "Female"
  }, {
    "id": 4,
    "first_name": "Teddie",
    "last_name": "Ceci",
    "email": "tceci3@shutterfly.com",
    "gender": "Male"
  }, {
    "id": 5,
    "first_name": "Noreen",
    "last_name": "Authers",
    "email": "nauthers4@bandcamp.com",
    "gender": "Genderqueer"
  }, {
    "id": 6,
    "first_name": "Jessalin",
    "last_name": "Cordobes",
    "email": "jcordobes5@list-manage.com",
    "gender": "Agender"
  }, {
    "id": 7,
    "first_name": "Kristoffer",
    "last_name": "Mapother",
    "email": "kmapother6@qq.com",
    "gender": "Genderqueer"
  }, {
    "id": 8,
    "first_name": "Krishnah",
    "last_name": "Stonbridge",
    "email": "kstonbridge7@google.com.hk",
    "gender": "Genderfluid"
  }, {
    "id": 9,
    "first_name": "Toma",
    "last_name": "Rolfo",
    "email": "trolfo8@msu.edu",
    "gender": "Non-binary"
  }, {
    "id": 10,
    "first_name": "Merissa",
    "last_name": "Foreman",
    "email": "mforeman9@weebly.com",
    "gender": "Genderqueer"
  }, {
    "id": 11,
    "first_name": "Farris",
    "last_name": "Gingle",
    "email": "fginglea@meetup.com",
    "gender": "Agender"
  }, {
    "id": 12,
    "first_name": "Robinia",
    "last_name": "Sirey",
    "email": "rsireyb@blinklist.com",
    "gender": "Male"
  }, {
    "id": 13,
    "first_name": "Isador",
    "last_name": "Ingarfield",
    "email": "iingarfieldc@columbia.edu",
    "gender": "Female"
  }, {
    "id": 14,
    "first_name": "Carlina",
    "last_name": "Crucitti",
    "email": "ccrucittid@phpbb.com",
    "gender": "Female"
  }, {
    "id": 15,
    "first_name": "Leslie",
    "last_name": "Burkitt",
    "email": "lburkitte@army.mil",
    "gender": "Male"
  }, {
    "id": 16,
    "first_name": "Lonnard",
    "last_name": "Gosdin",
    "email": "lgosdinf@whitehouse.gov",
    "gender": "Bigender"
  }, {
    "id": 17,
    "first_name": "Alexine",
    "last_name": "Alejandri",
    "email": "aalejandrig@ihg.com",
    "gender": "Agender"
  }, {
    "id": 18,
    "first_name": "Kate",
    "last_name": "McAllen",
    "email": "kmcallenh@moonfruit.com",
    "gender": "Non-binary"
  }, {
    "id": 19,
    "first_name": "Merle",
    "last_name": "Clough",
    "email": "mcloughi@samsung.com",
    "gender": "Male"
  }, {
    "id": 20,
    "first_name": "Manolo",
    "last_name": "Sambath",
    "email": "msambathj@shareasale.com",
    "gender": "Genderqueer"
  }, {
    "id": 21,
    "first_name": "Ashlan",
    "last_name": "Etty",
    "email": "aettyk@arizona.edu",
    "gender": "Bigender"
  }, {
    "id": 22,
    "first_name": "Carolus",
    "last_name": "Wardingley",
    "email": "cwardingleyl@de.vu",
    "gender": "Female"
  }, {
    "id": 23,
    "first_name": "Virginie",
    "last_name": "Jeandot",
    "email": "vjeandotm@dot.gov",
    "gender": "Non-binary"
  }, {
    "id": 24,
    "first_name": "Clemmie",
    "last_name": "Drieu",
    "email": "cdrieun@boston.com",
    "gender": "Agender"
  }, {
    "id": 25,
    "first_name": "Janifer",
    "last_name": "O'Halleghane",
    "email": "johalleghaneo@kickstarter.com",
    "gender": "Non-binary"
  }, {
    "id": 26,
    "first_name": "Evangelina",
    "last_name": "Pepin",
    "email": "epepinp@foxnews.com",
    "gender": "Bigender"
  }, {
    "id": 27,
    "first_name": "Melli",
    "last_name": "Yole",
    "email": "myoleq@multiply.com",
    "gender": "Female"
  }, {
    "id": 28,
    "first_name": "Dawn",
    "last_name": "Grinston",
    "email": "dgrinstonr@ibm.com",
    "gender": "Genderqueer"
  }, {
    "id": 29,
    "first_name": "Hillie",
    "last_name": "Shoosmith",
    "email": "hshoosmiths@nbcnews.com",
    "gender": "Non-binary"
  }, {
    "id": 30,
    "first_name": "Frances",
    "last_name": "Sive",
    "email": "fsivet@indiatimes.com",
    "gender": "Bigender"
  }, {
    "id": 31,
    "first_name": "Fred",
    "last_name": "Moorhead",
    "email": "fmoorheadu@geocities.jp",
    "gender": "Agender"
  }, {
    "id": 32,
    "first_name": "Fannie",
    "last_name": "Bellany",
    "email": "fbellanyv@uol.com.br",
    "gender": "Non-binary"
  }, {
    "id": 33,
    "first_name": "Park",
    "last_name": "Arnal",
    "email": "parnalw@shop-pro.jp",
    "gender": "Genderqueer"
  }, {
    "id": 34,
    "first_name": "Gabriela",
    "last_name": "Laugheran",
    "email": "glaugheranx@discovery.com",
    "gender": "Bigender"
  }, {
    "id": 35,
    "first_name": "Christabella",
    "last_name": "Wisher",
    "email": "cwishery@wufoo.com",
    "gender": "Male"
  }, {
    "id": 36,
    "first_name": "Janina",
    "last_name": "Snelgar",
    "email": "jsnelgarz@geocities.com",
    "gender": "Male"
  }, {
    "id": 37,
    "first_name": "Friederike",
    "last_name": "Andrelli",
    "email": "fandrelli10@deliciousdays.com",
    "gender": "Non-binary"
  }, {
    "id": 38,
    "first_name": "Auroora",
    "last_name": "State",
    "email": "astate11@ftc.gov",
    "gender": "Polygender"
  }, {
    "id": 39,
    "first_name": "Norman",
    "last_name": "Zum Felde",
    "email": "nzumfelde12@newsvine.com",
    "gender": "Agender"
  }, {
    "id": 40,
    "first_name": "Sher",
    "last_name": "Labdon",
    "email": "slabdon13@berkeley.edu",
    "gender": "Genderfluid"
  }, {
    "id": 41,
    "first_name": "Ruprecht",
    "last_name": "Kingcote",
    "email": "rkingcote14@twitpic.com",
    "gender": "Male"
  }, {
    "id": 42,
    "first_name": "Jacquelynn",
    "last_name": "Aneley",
    "email": "janeley15@zimbio.com",
    "gender": "Female"
  }, {
    "id": 43,
    "first_name": "Doretta",
    "last_name": "Filler",
    "email": "dfiller16@istockphoto.com",
    "gender": "Female"
  }, {
    "id": 44,
    "first_name": "Jody",
    "last_name": "Dunklee",
    "email": "jdunklee17@oaic.gov.au",
    "gender": "Agender"
  }, {
    "id": 45,
    "first_name": "Alis",
    "last_name": "Broadway",
    "email": "abroadway18@narod.ru",
    "gender": "Polygender"
  }, {
    "id": 46,
    "first_name": "Sal",
    "last_name": "Berresford",
    "email": "sberresford19@list-manage.com",
    "gender": "Polygender"
  }, {
    "id": 47,
    "first_name": "Rikki",
    "last_name": "Haffenden",
    "email": "rhaffenden1a@deliciousdays.com",
    "gender": "Male"
  }, {
    "id": 48,
    "first_name": "Amalle",
    "last_name": "Bulloch",
    "email": "abulloch1b@dropbox.com",
    "gender": "Genderqueer"
  }, {
    "id": 49,
    "first_name": "Alphonso",
    "last_name": "Gillbey",
    "email": "agillbey1c@cnbc.com",
    "gender": "Bigender"
  }, {
    "id": 50,
    "first_name": "Donia",
    "last_name": "Gershom",
    "email": "dgershom1d@jalbum.net",
    "gender": "Female"
  }, {
    "id": 51,
    "first_name": "Christabel",
    "last_name": "Basnall",
    "email": "cbasnall1e@time.com",
    "gender": "Non-binary"
  }, {
    "id": 52,
    "first_name": "Andria",
    "last_name": "Whitecross",
    "email": "awhitecross1f@tmall.com",
    "gender": "Polygender"
  }, {
    "id": 53,
    "first_name": "Anne-marie",
    "last_name": "Busen",
    "email": "abusen1g@ted.com",
    "gender": "Female"
  }, {
    "id": 54,
    "first_name": "Delly",
    "last_name": "Perton",
    "email": "dperton1h@dailymotion.com",
    "gender": "Polygender"
  }, {
    "id": 55,
    "first_name": "Ambur",
    "last_name": "McBryde",
    "email": "amcbryde1i@weibo.com",
    "gender": "Male"
  }, {
    "id": 56,
    "first_name": "Bernete",
    "last_name": "Crosfeld",
    "email": "bcrosfeld1j@usgs.gov",
    "gender": "Non-binary"
  }, {
    "id": 57,
    "first_name": "Lori",
    "last_name": "Siggery",
    "email": "lsiggery1k@jalbum.net",
    "gender": "Non-binary"
  }, {
    "id": 58,
    "first_name": "Carlen",
    "last_name": "Lindermann",
    "email": "clindermann1l@baidu.com",
    "gender": "Genderfluid"
  }, {
    "id": 59,
    "first_name": "Maurie",
    "last_name": "Simnett",
    "email": "msimnett1m@gnu.org",
    "gender": "Non-binary"
  }, {
    "id": 60,
    "first_name": "Auguste",
    "last_name": "Kyme",
    "email": "akyme1n@europa.eu",
    "gender": "Genderfluid"
  }, {
    "id": 61,
    "first_name": "Aurea",
    "last_name": "Jeandon",
    "email": "ajeandon1o@topsy.com",
    "gender": "Bigender"
  }, {
    "id": 62,
    "first_name": "Liliane",
    "last_name": "Wellsman",
    "email": "lwellsman1p@netvibes.com",
    "gender": "Agender"
  }, {
    "id": 63,
    "first_name": "Arie",
    "last_name": "Swapp",
    "email": "aswapp1q@vistaprint.com",
    "gender": "Genderfluid"
  }, {
    "id": 64,
    "first_name": "Bowie",
    "last_name": "Aubery",
    "email": "baubery1r@hostgator.com",
    "gender": "Genderqueer"
  }, {
    "id": 65,
    "first_name": "Moise",
    "last_name": "Habbin",
    "email": "mhabbin1s@youku.com",
    "gender": "Non-binary"
  }, {
    "id": 66,
    "first_name": "Ailene",
    "last_name": "Brierley",
    "email": "abrierley1t@gnu.org",
    "gender": "Non-binary"
  }, {
    "id": 67,
    "first_name": "Devi",
    "last_name": "Pala",
    "email": "dpala1u@bizjournals.com",
    "gender": "Non-binary"
  }, {
    "id": 68,
    "first_name": "Brande",
    "last_name": "Landall",
    "email": "blandall1v@hp.com",
    "gender": "Bigender"
  }, {
    "id": 69,
    "first_name": "Halli",
    "last_name": "Dunne",
    "email": "hdunne1w@youtube.com",
    "gender": "Genderqueer"
  }, {
    "id": 70,
    "first_name": "Homerus",
    "last_name": "Adamiec",
    "email": "hadamiec1x@creativecommons.org",
    "gender": "Female"
  }, {
    "id": 71,
    "first_name": "Farlee",
    "last_name": "Bottinelli",
    "email": "fbottinelli1y@tuttocitta.it",
    "gender": "Non-binary"
  }, {
    "id": 72,
    "first_name": "Rianon",
    "last_name": "Tadgell",
    "email": "rtadgell1z@soup.io",
    "gender": "Genderfluid"
  }, {
    "id": 73,
    "first_name": "Daffi",
    "last_name": "MacGuigan",
    "email": "dmacguigan20@samsung.com",
    "gender": "Bigender"
  }, {
    "id": 74,
    "first_name": "Stella",
    "last_name": "Eles",
    "email": "seles21@wordpress.org",
    "gender": "Non-binary"
  }, {
    "id": 75,
    "first_name": "Harriott",
    "last_name": "Alfuso",
    "email": "halfuso22@whitehouse.gov",
    "gender": "Non-binary"
  }, {
    "id": 76,
    "first_name": "Alford",
    "last_name": "Riveles",
    "email": "ariveles23@feedburner.com",
    "gender": "Genderqueer"
  }, {
    "id": 77,
    "first_name": "Bealle",
    "last_name": "Wellum",
    "email": "bwellum24@topsy.com",
    "gender": "Bigender"
  }, {
    "id": 78,
    "first_name": "Cull",
    "last_name": "Pouton",
    "email": "cpouton25@newyorker.com",
    "gender": "Male"
  }, {
    "id": 79,
    "first_name": "Silvio",
    "last_name": "Buckner",
    "email": "sbuckner26@opera.com",
    "gender": "Polygender"
  }, {
    "id": 80,
    "first_name": "Jourdain",
    "last_name": "Sporton",
    "email": "jsporton27@cornell.edu",
    "gender": "Polygender"
  }, {
    "id": 81,
    "first_name": "Baird",
    "last_name": "Dennison",
    "email": "bdennison28@amazonaws.com",
    "gender": "Male"
  }, {
    "id": 82,
    "first_name": "Jared",
    "last_name": "Lanceley",
    "email": "jlanceley29@wikipedia.org",
    "gender": "Polygender"
  }, {
    "id": 83,
    "first_name": "Korie",
    "last_name": "Kubacki",
    "email": "kkubacki2a@topsy.com",
    "gender": "Female"
  }, {
    "id": 84,
    "first_name": "Angelle",
    "last_name": "Ellen",
    "email": "aellen2b@github.com",
    "gender": "Genderfluid"
  }, {
    "id": 85,
    "first_name": "Lesley",
    "last_name": "Pardi",
    "email": "lpardi2c@typepad.com",
    "gender": "Genderfluid"
  }, {
    "id": 86,
    "first_name": "Molli",
    "last_name": "Treby",
    "email": "mtreby2d@archive.org",
    "gender": "Genderqueer"
  }, {
    "id": 87,
    "first_name": "Timofei",
    "last_name": "Chater",
    "email": "tchater2e@weather.com",
    "gender": "Genderfluid"
  }, {
    "id": 88,
    "first_name": "Van",
    "last_name": "Brabin",
    "email": "vbrabin2f@360.cn",
    "gender": "Bigender"
  }, {
    "id": 89,
    "first_name": "Rivkah",
    "last_name": "Riach",
    "email": "rriach2g@eepurl.com",
    "gender": "Genderqueer"
  }, {
    "id": 90,
    "first_name": "Moss",
    "last_name": "Camois",
    "email": "mcamois2h@google.cn",
    "gender": "Non-binary"
  }, {
    "id": 91,
    "first_name": "Lorianna",
    "last_name": "Gianulli",
    "email": "lgianulli2i@columbia.edu",
    "gender": "Genderfluid"
  }, {
    "id": 92,
    "first_name": "Carlen",
    "last_name": "Handsheart",
    "email": "chandsheart2j@dailymail.co.uk",
    "gender": "Genderfluid"
  }, {
    "id": 93,
    "first_name": "Maynord",
    "last_name": "Turbefield",
    "email": "mturbefield2k@sina.com.cn",
    "gender": "Genderqueer"
  }, {
    "id": 94,
    "first_name": "Cort",
    "last_name": "Stanier",
    "email": "cstanier2l@printfriendly.com",
    "gender": "Genderqueer"
  }, {
    "id": 95,
    "first_name": "Maynord",
    "last_name": "Rowes",
    "email": "mrowes2m@pagesperso-orange.fr",
    "gender": "Female"
  }, {
    "id": 96,
    "first_name": "Nil",
    "last_name": "Parris",
    "email": "nparris2n@spiegel.de",
    "gender": "Male"
  }, {
    "id": 97,
    "first_name": "Agnese",
    "last_name": "Raynor",
    "email": "araynor2o@privacy.gov.au",
    "gender": "Polygender"
  }, {
    "id": 98,
    "first_name": "Bethena",
    "last_name": "Toten",
    "email": "btoten2p@wix.com",
    "gender": "Polygender"
  }, {
    "id": 99,
    "first_name": "Lanie",
    "last_name": "Burdikin",
    "email": "lburdikin2q@indiatimes.com",
    "gender": "Female"
  }, {
    "id": 100,
    "first_name": "Reece",
    "last_name": "Klimpke",
    "email": "rklimpke2r@wikispaces.com",
    "gender": "Bigender"
  }]